version: '3'
services: 
  db:
    image: postgres
    ports: 
      - 5432:5432
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRESS_DB: postgres
  resource-service:
    depends_on: 
      - db
    build: .
    volumes: 
      - .
    ports: 
      - 4000:4000
