version: '3'
services: 
  postgres:
    image: "postgres"
    environment: 
      POSTGRES_PASSWORD: "secret"
    ports:
      - "5432:5432"
  resource-service:
    build: .
    ports: 
      - "4000:4000"
  adminer:
    image: "adminer"
    ports: 
      - "8080:8080"
